[View in Colaboratory](https://colab.research.google.com/github/oshoolumuyiwa/pandas/blob/master/Introduction_to_computational_graph_autograd.ipynb)

# **Installation of PyTorch**

In [0]:
# Bookkeeping
# http://pytorch.org/
from os import path
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())

accelerator = 'cu80' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.3.0.post4-{platform}-linux_x86_64.whl torchvision


In [0]:
import torch 

# 1 Creating a matrix with numpy vs pytorch
create an array by passing a list argument.
Array is made up of "nested list".

In [8]:
a_list = [1,2]
b_list = [3,4]
print(a_list)
print(b_list)

[1, 2]
[3, 4]


In [9]:
array = [a_list,b_list]
print(array)

[[1, 2], [3, 4]]


In [10]:
a = [[1,2],[3,4]]
print(a)

[[1, 2], [3, 4]]


In [13]:
type(a)

list

In [12]:
print(a.shape) #Not an array, hence no shape

AttributeError: ignored

**Create an array**

In [0]:
# import Numpy library
import numpy as np

In [16]:
a_array = np.array(a)  #N-dimensional array
#Task print array
print(a_array)

[[1 2]
 [3 4]]


In [19]:
# Convert to PyTorch Tensor
T_array = torch.Tensor(a_array)
#Task print array
print(T_array)


 1  2
 3  4
[torch.FloatTensor of size 2x2]



In [20]:
print(type(a_array)) # N-dimensional arrays"because they can have any number of dimensions."
print(a_array.dtype) # Datatype of array

<class 'numpy.ndarray'>
int64


In [21]:
print(a_array.shape)

(2, 2)


**Others**

In [22]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
torch.ones((2,2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [24]:
np.random.rand(2,2)

array([[0.90099715, 0.09628291],
       [0.83135945, 0.089932  ]])

In [1]:
torch.rand(2,2)

NameError: ignored

**Seed for Reproducibility**: replication of exact result across experiments.


In [26]:
np.random.seed(0) # 0,1,2,3......
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [28]:
# Seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [29]:
# No seed
#np.random.seed(0)
np.random.rand(2,2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [30]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2,2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [32]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2,2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

**Linking Numpy with Torch**

In [34]:
# Numpy array
np_array = np.ones((2,2))
#Task print
print(np_array)

[[1. 1.]
 [1. 1.]]


In [35]:
# Convert to Torch Tensor 
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]



In [36]:
print(type(torch_tensor))

<class 'torch.DoubleTensor'>


In [40]:
# Testing datatype
#test_arr_datatype = np.ones((2,2), dtype=np.int8) # try int32
test_arr_datatype = np.ones((2,2)) # try int32
# Task: convert to torch tensor
help(np.ones((2,2)))
print(type(test_arr_datatype))


Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

Torch cannot convert **all kind of numpy** to Tensor. Approved datatype 


*   double


*   float

*   int64
*   uint8


*   int32


# **Torch to Numpy**

In [42]:
torch_tensor = torch.ones((3,3))
# Task print

print(torch_tensor)


 1  1  1
 1  1  1
 1  1  1
[torch.FloatTensor of size 3x3]



In [43]:
type(torch_tensor)

torch.FloatTensor

In [45]:
#convertion
torch_to_numpy = torch_tensor.numpy()
#Task print(type)
print(type(torch_to_numpy))
print(torch_to_numpy)

<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Slicing**

In [46]:
a

[[1, 2], [3, 4]]

In [47]:
print(a[0])

[1, 2]


In [48]:
print(a[1])

[3, 4]


In [49]:
print(a[0][1])

2


In [0]:
nums = list(range(5))  # Prints "[0, 1, 2, 3, 4]"

In [51]:
nums

[0, 1, 2, 3, 4]

In [52]:
print(nums[2:4])  # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"

[2, 3]


In [53]:
print(nums[2:]) # Get a slice from index 2 to the end; prints "[2, 3, 4]"

[2, 3, 4]


In [54]:
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"

[0, 1]


In [55]:
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"

[0, 1, 2, 3, 4]


In [56]:
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"

[0, 1, 2, 3]


In [0]:
nums[2:4] = [8, 9]        # Assign a new sublist to a slice

**Matrix of operations**

In [60]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)

[[1. 2.]
 [3. 4.]]


In [61]:
print(y)

[[5. 6.]
 [7. 8.]]


In [63]:
print(x + y) # or print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [64]:
print(x - y) # or print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [65]:
print(x * y) # or print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


In [66]:
print( x / y) # or print(np.multiply(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [67]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


# **Broadcasting** 
The term ‘broadcasting’ refers to the property of NumPy module which comes into play when doing arithmetic operations on the arrays and matrices.
NumPy broadcasting lets you perform, in efficient way, element-wise operations on arrays, as long as dimensions of those arrays are considered "**compatible"** in some sense.

![alt text](https://i.stack.imgur.com/JcKv1.png)

In [68]:
x = np.array([0,10,20,30])
print(x)

[ 0 10 20 30]


In [69]:
x = np.reshape(x, (len(x),1))
print(x)
print(x.shape)

[[ 0]
 [10]
 [20]
 [30]]
(4, 1)


In [70]:
y = np.array([0,1,2])
y = np.reshape(y, (1, len(y)))
print(y)
print(y.shape)

[[0 1 2]]
(1, 3)


In [71]:
print(x + y)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


General rule

*   (m,n) + (1,n) => (m,n)

*   (m,n) - (1,n) => (m,n)

*   (m,n)  * (1,n) => (m,n)
*   (m,n) / (1,n) => (m,n)


> (m,1) + R(scalar) = (m,1)


Introduction to Variable and Autograd

**Dependencies for PyTorch**

In [0]:
# import
import torch
from torch import FloatTensor

**Variables**



*     A Variable wraps a Tensor.
 
*  Allow accumulation of gradients.








In [0]:
# import Variable class
from torch.autograd import Variable

In [99]:
a = Variable(torch.ones(2,2), requires_grad=True) #Differeniatible
#Task: print Variable
print(a)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [100]:
# The tensor is not a variable
torch.ones(2,2)


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [0]:
# create another Variable "b" and perform mathematical operations
#add, multiply then up

Check slides for computational graph image.

### **Define the leaf nodes**

In [101]:
# Define the leaf nodes
x0 = Variable(FloatTensor([-1]))
x1 = Variable(FloatTensor([-2]))
print(x0)
print(x1)

Variable containing:
-1
[torch.FloatTensor of size 1]

Variable containing:
-2
[torch.FloatTensor of size 1]



**Initialize the weights**

We must set the **requires_grad attribute to True**, otherwise, these Variables won’t be included in the computation graph, and no gradients would be computed for them (and other variables, that depend on these particular variables for gradient flow).

In [0]:
weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (2, -3, -3)]

In [103]:
for i in weights: print(i)

Variable containing:
 2
[torch.FloatTensor of size 1]

Variable containing:
-3
[torch.FloatTensor of size 1]

Variable containing:
-3
[torch.FloatTensor of size 1]



**Unpack the weights for nicer assignment**

In [104]:

w0, w1, w2 = weights
print(w0)
print(w1)
print(w2)

Variable containing:
 2
[torch.FloatTensor of size 1]

Variable containing:
-3
[torch.FloatTensor of size 1]

Variable containing:
-3
[torch.FloatTensor of size 1]



In [105]:
for i in weights: print(i.requires_grad)

True
True
True


In [0]:
a = w0 * x0
b = w1 * x1
c = a + b
d = c + w2
e = d * (-1)
f = torch.exp(e)
g = f + 1
h = 1 / g

In [107]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

Variable containing:
-2
[torch.FloatTensor of size 1]

Variable containing:
 6
[torch.FloatTensor of size 1]

Variable containing:
 4
[torch.FloatTensor of size 1]

Variable containing:
 1
[torch.FloatTensor of size 1]

Variable containing:
-1
[torch.FloatTensor of size 1]

Variable containing:
 0.3679
[torch.FloatTensor of size 1]

Variable containing:
 1.3679
[torch.FloatTensor of size 1]

Variable containing:
 0.7311
[torch.FloatTensor of size 1]



Well, so far the variable objects are the nodes of the graph. There is a function object(grad_fn) of each variable that forms the node of the graph.

In [93]:
print(a.grad_fn)
print(b.grad_fn)
print(c.grad_fn)
print(d.grad_fn)
print(e.grad_fn)
print(f.grad_fn)
print(g.grad_fn)
print(h.grad_fn)

In [0]:
h.backward()

In [110]:
for index, weight in enumerate(weights, start=0):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to L: {gradient: .1f}") #round up

Gradient of w0 w.r.t to L: -0.2
Gradient of w1 w.r.t to L: -0.4
Gradient of w2 w.r.t to L:  0.2


In [0]:
a = Variable(FloatTensor([4]))

In [0]:
weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (2, 5, 9, 7)]

In [0]:
w1, w2, w3, w4 = weights

In [0]:
b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
L = (10 - d)

In [0]:
print(b.grad_fn)
print(c.grad_fn)
print(d.grad_fn)
print(L.grad_fn)

In [0]:
L.backward()

In [109]:
for index, weight in enumerate(weights, start=1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to L: {gradient}")

Gradient of w1 w.r.t to L: -0.19661197066307068
Gradient of w2 w.r.t to L: -0.39322394132614136
Gradient of w3 w.r.t to L: 0.19661197066307068
